### ISSUE TITLE
README.md has broken badge "Dependencies status"

### ISSUE THREAD

**Issue by jsyrjala** [clj-commons/claypoole#49]
```
[![Dependencies Status](http://jarkeeper.com/TheClimateCorporation/claypoole/status.svg)](http://jarkeeper.com/TheClimateCorporation/claypoole)
```

http://jarkeeper.com no longer seem to point to anything

**Comment by ieugen** [comment]
This seems to have been fixed. 
It is pointing to the (old) clojars repo. 
We will migrate to a new group-id, as part of clj-commons move: org.clj-commons/claypool .
Please reopen if you think this is not done.
